name: pr

on:
  push:
    branches: [ next ]

  workflow_dispatch:

concurrency: prr:pre-release

jobs:
  pr:

    environment: NPM
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npx pr-release pr --verbose --target main --source next --compact
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # The following will publish a pre-release to npm
    - run: npx pr-release extract-changelog --target main --source next --compact --out
    - run: npm version --no-verify --no-commit-hooks --no-git-tag-version $(cat ./.pr-release/nextVersion)
    - run: npm version --no-verify --no-commit-hooks --no-git-tag-version prerelease --preid=unstable
    - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      name: Setup NPM Auth
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - run: npm publish --tag=unstable
      name: Publish
